CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CPP_EXCEPTIONS=n
CONFIG_CPP_RTTI=n
CONFIG_REQUIRES_FULL_LIBCPP=y  # Only enable on embedded hardware (TEENSY41)

CONFIG_RTIO=y


# ----------------- Thread configurations -------------------
# Scheduler
CONFIG_SCHED_EDF=y
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=10        # 10ms timeslice per thread best-effort

# Stack e thread
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NUM_PREEMPT_PRIORITIES=16
CONFIG_NUM_COOP_PRIORITIES=2    # per thread di init

# Interrupt latency
CONFIG_ZERO_LATENCY_IRQS=y      # ISR critiche non mascherabili

# Debug (disabilitare in produzione)
CONFIG_THREAD_ANALYZER=y
CONFIG_TRACING=y                # per analizzare i context switch con Percepio Tracealyzer


# ------------------ Flash e Storage ------------------
# 1. Abilita il supporto hardware per la memoria flash
CONFIG_FLASH=y

# 2. Abilita il driver del simulatore di flash
CONFIG_FLASH_SIMULATOR=y

# 3. Abilita il layout delle pagine di flash (richiesto da FCB)
CONFIG_FLASH_PAGE_LAYOUT=y

# 4. Abilita la mappa della memoria flash (richiesto da FCB)
CONFIG_FLASH_MAP=y

# 5. Abilita il Flash Circular Buffer (FCB)
CONFIG_FCB=y

# ------------------ Settings Subsystem ------------------
# Abilita il Settings Subsystem
CONFIG_SETTINGS=y

# Seleziona esplicitamente FCB come backend per il Settings Subsystem
CONFIG_SETTINGS_FCB=y

# ------------------ Logging ------------------
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_IMMEDIATE=y