name: Infinity-autopilot SCA

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'platform/**'
      - 'lib/**'
  pull_request:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build-configs:
          - {zephyr-board: "native_sim/native/64", target-platform: "SITL"}
          - {zephyr-board: "teensy41", target-platform: "TEENSY41"}

    env:
      ZEPHYR_SDK_INSTALL_DIR: /home/runner/zephyr-sdk
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          path: infinity
          submodules: 'recursive' 

      # Cache dell'SDK e del workspace west
      - name: Cache SDK e west
        uses: actions/cache@v6
        with:
          path: |
            /home/runner/zephyr-sdk
            /home/runner/.cache/pip
            ${{ github.workspace }}/modules
            ${{ github.workspace }}/zephyr
          key: zephyr-${{ runner.os }}-${{ hashFiles('infinity/west.yml') }}
          restore-keys: |
            zephyr-${{ runner.os }}-

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: infinity
          toolchains: arm-zephyr-eabi   # cambia se usi un'altra architettura

      - name: Install CodeChecker
        run: |
          pip install codechecker
          # verifica che sia nel PATH
          which CodeChecker || codechecker --version

      - name: Build with SCA and CodeChecker
        working-directory: infinity
        run: |
          west build -b ${{ matrix.build-configs.zephyr-board }} -p always . -- \
            -DTARGET_PLATFORM=${{ matrix.build-configs.target-platform }} \
            -DZEPHYR_SCA_VARIANT=codechecker \
            -DCODECHECKER_EXPORT=html \
            -DCODECHECKER_ANALYZE_JOBS=4

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: codechecker-reports-${{ matrix.build-configs.target-platform }}-${{ github.sha }}
          path: ${{ github.workspace }}/infinity/build/sca/codechecker/
          if-no-files-found: error
          retention-days: 7